hanaablog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from pages.sitemaps import PostSitemap
#from marketing.views import email_list_signup

sitemaps = {'posts':PostSitemap,}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='home')),
    #path('subscribe/', email_list_signup, name="subscribe"),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from .views import blog_category, gallery, Photo, video
from .feeds import LatestPostsFeed
from marketing.views import email_list_signup

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    #path('category/<str:cats>/', CategoryView, name= 'category'),
    path("category/<slug:category_slug>/", views.blog_category, name='categories'),
    path('photo/<str:pk>/', views.viewPhoto, name='photo'),
    path('gallery/', views.gallery, name='gallery'),
    path('video/', views.video, name='video'),
    path('post_list/', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>',views.post_list, name='post_list_by_tag'),
    #path('post_list/',views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('subscribe/', email_list_signup, name="subscribe"),
    path('feed/',LatestPostsFeed(),name='post_feed'),
    #path('about', views.about, name='about'),
    #path('services', views.services, name='services'),
    #path('contact', views.contact, name='contact'),
]

pages/templates/blogpost/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HanaaQuilt | HanaaQuilt Blog</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy&amp;display=swap">
    <!-- Lightbox-->
    <link rel="stylesheet" href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v10.0&appId=2892710120976873&autoLogAppEvents=1" nonce="R7qUWPMW"></script>
  <script>
   function myFunction() {
   var x = document.URL;
   document.getElementById("quilt").src = 'https://www.facebook.com/plugins/share_button.php?href='+x+'&layout=button_count&size=large&mobile_iframe=true&width=83&height=28&appId';
  }
  </script>
  </head>
  <body onload="myFunction()">
    <!-- navbar-->
    <header class="header">                   
      <nav class="navbar navbar-expand-lg navbar-light py-4 index-forward bg-white">
        <div class="container d-flex justify-content-center justify-content-lg-between align-items-center">
          {% for team in teams %}
            <ul class="list-inline small mb-0 text-dark d-none d-lg-block">
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.facebook_link}}"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.instagram_link}}"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.youtube_link }}"><i class="fab fa-youtube"></i></a></li>
            </ul><a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'img/logo.jpg' %}" alt="..." width="150"></a><a class="reset-anchor text-small mb-0 h6 d-none d-lg-block" href="mailto:Juliette@email.com"><i class="far fa-envelope mr-2 text-primary"></i>{% for team in teams %}{{ team.number}}{% endfor %}</a>
          {% endfor %}

        </div>
      </nav>
      <nav class="navbar navbar-expand-lg navbar-light border-top border-bottom border-light">
        <div class="container">
         
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span></span><span></span><span></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link" href="{% url 'home:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link" href="{% url 'home:post_list' %}">Blogpost</a>
              </li>
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link" href="{% url 'home:gallery' %}">Gallery </a>
              </li>
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link" href="{% url 'home:gallery' %}">Video </a>
              </li>
              <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                <div class="dropdown-menu mt-2" aria-labelledby="pages">{% for category in menu_categories %}<a class="dropdown-item" href="{% url 'home:categories' category.slug %}">{{ category.title}}</a>
                {% endfor %}
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
{% block content %}

{% endblock %}
          <div class="col-lg-3">
            <!-- About category-->
            <div class="card rounded-0 border-0 bg-light mb-4 py-lg-4">
              <div class="card-body text-center">
              
              {% for team in teams %}
                  <h2 class="h3 mb-3">About me</h2><img class="rounded-circle mb-3" src="{{ team.photo.url}}" alt="..." width="100">
                  <p class="text-small text-muted">{{ team.number }}</p>
                  <p class="text-small text-muted">{% total_posts %} posts</p>
                  <ul class="list-inline small mb-0 text-dark">
                    <li class="list-inline-item"><a class="reset-anchor" href="{{team.facebook_link}}"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="list-inline-item"><a class="reset-anchor" href="{{team.instagram_link}}"><i class="fab fa-instagram"></i></a></li>
                    <li class="list-inline-item"><a class="reset-anchor" href="{{team.youtube_link}}"><i class="fab fa-youtube"></i></a></li>
                  </ul>
                {% endfor %}
              </div>
            </div>
            <!-- Recent posts-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0">
                <h2 class="h5 mb-3">Recent posts</h2>
                {% show_latest_posts 3 %}
              </div>
            </div>
            <!-- Categories-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0">
              {% get_most_commented_posts as most_commented_posts %}
                <ul>
                {% for post in most_commented_posts %}
                <li>
                  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
                {% endfor %}
              </ul>
              </div>
            </div>
            <!-- Tags-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0">
                <h2 class="h5 mb-3">Tags cloud</h2>
                <ul class="list-inline">
                  {% for post in posts %}
                    {% for tag in post.tags.all %}

                      <li class="list-inline-item my-1 mr-2"><a class="sidebar-tag-link" href="{% url 'home:post_list_by_tag' tag.slug %}">
                      {{ tag.name }}</a>
                     
                      </li>
                       {% if not forloop.last %} {% endif %}
                    {% endfor %}
                  {% endfor %}
                </ul>
              </div>
            </div>
            <!-- Ad-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0"><a class="d-block" href="#"><img class="img-fluid" src="img/banner.jpg" alt=""></a></div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <footer class="py-4" style="background: #111">
      <div class="container text-center">
        <div class="row align-items-center">
          <div class="col-md-4 text-lg-left"><img src="{% static 'img/logo.png' %}" alt="..." width="120"></div>
          <div class="col-md-4 text-center">
            <div class="d-flex align-items-center flex-wrap justify-content-center">
              <h6 class="text-muted mb-0 py-2 mr-3">Follow me<span class="ml-3">-</span></h6>
              <ul class="list-inline small mb-0 text-white">
                    <li class="list-inline-item"><a class="reset-anchor" href="{{team.facebook_link}}"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="list-inline-item"><a class="reset-anchor" href="{{team.instagram_link}}"><i class="fab fa-instagram"></i></a></li>
                    <li class="list-inline-item"><a class="reset-anchor" href="{{team.youtube_link}}"><i class="fab fa-youtube"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4 text-lg-right">
            <p class="mb-0 text-muted text-small text-heading">Template designed by <a href="https://bootstraptemple.com/p/juliette" class="text-reset">Bootstrap Temple</a>. </p>
          </div>
        </div>
      </div>
    </footer>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </body>
</html>

pages/templates/blogpost/base2.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HanaaQuilt Blog | Hanaa's Blog</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy&amp;display=swap">
    <!-- Lightbox-->
    <link rel="stylesheet" href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <!-- navbar-->
    <header class="header">                   
      <nav class="navbar navbar-expand-lg navbar-light py-4 index-forward bg-white">
        <div class="container d-flex justify-content-center justify-content-lg-between align-items-center">
          <ul class="list-inline small mb-0 text-dark d-none d-lg-block">
            {% for team in teams %}
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.facebook_link }}"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.instagram_link }}"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.youtube_link }}"><i class="fab fa-youtube"></i></a></li>
            {% endfor %}
          </ul><a class="navbar-brand" href="#"><img src="{% static 'img/logo.jpg' %}" alt="..." width="180"></a><a class="reset-anchor text-small mb-0 h6 d-none d-lg-block" href="mailto:Juliette@email.com">{% for team in teams %}<i class="far fa-envelope mr-2 text-primary">{{ team.number}}</i>{% endfor %}</a>
        </div>
      </nav>
      <nav class="navbar navbar-expand-lg navbar-light border-top border-bottom border-light">
        <div class="container">
          <ul class="list-inline small mb-0 text-dark d-block d-lg-none">
            {% for team in teams %}
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.facebook_link }}"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.instagram_link }}"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="{{ team.youtube_link }}"><i class="fab fa-youtube"></i></a></li>
            {% endfor %}  
          </ul>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span></span><span></span><span></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link active" href="{% url 'home:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link" href="{% url 'home:post_list' %}">Blog list </a>
              </li>
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link" href="{% url 'home:gallery' %}">Gallery </a>
              </li>
              <li class="nav-item">
                <!-- Navbar link--><a class="nav-link" href="{% url 'home:video' %}">Video </a>
              </li>
              <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                <div class="dropdown-menu mt-2" aria-labelledby="pages">{% for category in menu_categories %}<a class="dropdown-item" href="{% url 'home:categories' category.slug %}">{{ category.title}}</a>
                {% endfor %}
                </div>
              
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
{% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
{% endif %}

{% block content %}

{% endblock %}

          <!-- Blog sidebar-->
          <div class="col-lg-3">
            <!-- About category-->
            <div class="card rounded-0 border-0 bg-light mb-4 py-lg-4">
              <div class="card-body text-center">
              
                  {% for team in teams %}
                    <h2 class="h3 mb-3">About me</h2><img class="rounded-circle mb-3" src="{{ team.photo.url }}" alt="..." width="100">
                    <p class="text-small text-muted">{{ team.number }}</p>
                    <p class="text-small text-muted">{% total_posts %} posts</p>

                    <ul class="list-inline small mb-0 text-dark">
                        <li class="list-inline-item"><a class="reset-anchor" href="{{ team.facebook_link }}"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a class="reset-anchor" href="{{ team.instagram_link }}"><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a class="reset-anchor" href="{{ team.youtube_link }}"><i class="fab fa-youtube"></i></a></li>
                    </ul>
                {% endfor %}
              </div>

            </div>
            <!-- Recent posts-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0">
                <h2 class="h5 mb-3">Recent posts</h2>
                {% show_latest_posts 3 %}
              </div>
            </div>
            <!-- Categories-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0">
                <h2 class="h5 mb-3">Trending comments</h2>
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                {% for post in most_commented_posts %}
                <li>
                  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
                {% endfor %}
              </ul>
              </div>
            </div>
            <!-- Tags-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0">
                <h2 class="h5 mb-3">Tags cloud</h2>
                <ul class="list-inline">
                  {% for post in posts %}
                    {% for tag in post.tags.all %}

                      <li class="list-inline-item my-1 mr-2"><a class="sidebar-tag-link" href="{% url 'home:post_list_by_tag' tag.slug %}">
                      {{ tag.name }}</a>
                      {% if not forloop.last %} {% endif %}
                      </li>
                    {% endfor %}
                  {% endfor %}
                </ul>
              </div>
            </div>
            <!-- Ad-->
            <div class="card rounded-0 border-0 mb-4">
              <div class="card-body p-0"><a class="d-block" href="#"><img class="img-fluid" src="{% static 'img/banner.jpg' %}" alt=""></a></div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="instagram-section-title d-none d-sm-block"><i class="fab fa-instagram mr-2"></i>Follow on Instagram @Juliette</div>
      <div class="container-fluid px-0">
        <div class="row">
          <div class="col-lg-2 col-4 p-0"><a class="d-block instagram-item" href="#"><img class="img-fluid" src="{% static 'img/instagram-1.jpg' %}" alt="">
              <div class="instagram-item-overlay"><i class="fab fa-instagram"></i></div></a></div>
          <div class="col-lg-2 col-4 p-0"><a class="d-block instagram-item" href="#"><img class="img-fluid" src="{% static 'img/instagram-2.jpg' %}" alt="">
              <div class="instagram-item-overlay"><i class="fab fa-instagram"></i></div></a></div>
          <div class="col-lg-2 col-4 p-0"><a class="d-block instagram-item" href="#"><img class="img-fluid" src="{% static 'img/instagram-3.jpg' %}" alt="">
              <div class="instagram-item-overlay"><i class="fab fa-instagram"></i></div></a></div>
          <div class="col-lg-2 col-4 p-0"><a class="d-block instagram-item" href="#"><img class="img-fluid" src="{% static 'img/instagram-4.jpg' %}" alt="">
              <div class="instagram-item-overlay"><i class="fab fa-instagram"></i></div></a></div>
          <div class="col-lg-2 col-4 p-0"><a class="d-block instagram-item" href="#"><img class="img-fluid" src="{% static 'img/instagram-5.jpg' %}" alt="">
              <div class="instagram-item-overlay"><i class="fab fa-instagram"></i></div></a></div>
          <div class="col-lg-2 col-4 p-0"><a class="d-block instagram-item" href="#"><img class="img-fluid" src="{% static 'img/instagram-6.jpg' %}" alt="">
              <div class="instagram-item-overlay"><i class="fab fa-instagram"></i></div></a></div>
        </div>
      </div>
    </section>
    <footer class="py-4" style="background: #111">
      <div class="container text-center">
        <div class="row align-items-center">
          <div class="col-md-4 text-lg-left"><img src="{% static 'img/logo.png' %}" alt="..." width="120"></div>
          <div class="col-md-4 text-center">
            <div class="d-flex align-items-center flex-wrap justify-content-center">
              <h6 class="text-muted mb-0 py-2 mr-3">Follow me<span class="ml-3">-</span></h6>
              <ul class="list-inline small mb-0 text-white">
              {% for team in teams %}
                <li class="list-inline-item"><a class="reset-anchor" href="{{ team.facebook_link }}"><i class="fab fa-facebook-f"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="{{ team.instagram_link }}"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="{{ team.youtube_link }}"><i class="fab fa-youtube"></i></a></li>
              {% endfor %}
              </ul>
            </div>
          </div>
          <div class="col-md-4 text-lg-right">
            <p class="mb-0 text-muted text-small text-heading">Template designed by <a href="https://bootstraptemple.com/p/juliette" class="text-reset">Bootstrap Temple</a>. </p>
          </div>
        </div>
      </div>

    </footer>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </body>
</html>

pages/templates/blogpost/categories.html
{% extends 'blogpost/base.html' %}
{% load static %}

{% block title %} HanaaQuilt Blog | {{ categories.title }}{% endblock title %}
{% block content %}
    <section class="py-5">
      <div class="container py-4">
        <div class="row">
          <!-- Blog listing-->
          <div class="col-lg-9 mb-5 mb-lg-0">
            <div class="row">
              {% for post in posts  %}
              <div class="col-lg-6 mb-5"><a class="d-block post-trending mb-4" href="{{post.get_absolute_url}}"><img class="img-fluid w-100" src="{{ post.blog_photo.url }}" alt=""/></a>
                <ul class="list-inline">

                  <li class="list-inline-item mr-2"><a class="category-link font-weight-normal" href="{{post.category.get_absolute_url}}">{{ post.category }}</a></li>

                  <li class="list-inline-item mx-2"><a class="text-uppercase meta-link font-weight-normal" href="#">{{ post.author.first_name }} {{ post.author.last_name }}</a></li>
                  <li class="list-inline-item mx-2"><a class="text-uppercase meta-link font-weight-normal" href="#">{{ post.publish }}</a></li>
                  {% for tag in post.tags.all %}
                  <li class="list-inline-item mx-2"><a class="text-uppercase meta-link font-weight-normal" href="{% url 'home:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                  {% if not forloop.last %} {% endif %}
                  </li>
                  {% endfor %}
                </ul>
                <h2 class="h3 mb-4"> <a class="d-block reset-anchor" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <p class="text-muted">{{ post.snippet }}</p><a class="btn btn-link p-0 read-more-btn" href="{{ post.get_absolute_url }}"><span>Read more</span><i class="fas fa-long-arrow-alt-right"></i></a>
              </div>
              {% endfor %}

            </div>
            <!-- Pagination-->
            {% include "pagination.html" with page=posts %}
          </div>
          <!-- Blog sidebar-->

{% endblock %}

pages/templates/blogpost/gallery.html
{% extends 'blogpost/base3.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load blog_tags %}
{% block content %}

<body class="m-5">

    <div class="container">
        <div class="row">
            <div class="col-md-3">

                <div class="card">
                    <div class="card-header">
                        Categories
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'home:gallery' %}">All</a>
                        </li>
                        {% for category in categories %}
                        <li class=" list-group-item">
                            <a href="{% url 'home:gallery' %}?category={{category.name}}">
                                {{category.name}}
                            </a>
                        </li>
                        {% endfor %}


                    </ul>
                </div>

            </div>
            <div class="col-md-9">
                <div class="row">

                    {% for photo in photos %}
                    <div class="col-md-4">
                        <div class="card my-2">
                            <div class="col">
                                    <div class="card shadow-sm">
                                        <img class="image-thumbail" src="{{ photo.image.url }}" alt="Card image cap">
                                        <div class="card-body">
                                        <p class="card-text"><small>Category: {{photo.category.name}}</small></p>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'home:photo' photo.id %}" class="btn btn-outline-dark btn-sm m-1">View</a></button>
                                            </div>
                                            <small class="text-muted"></small>
                                        </div>
                                        </div>
                                    </div>
                                    </div>
                        </div>
                    </div>
                    {% empty %}
                    <h3>No photos...</h3>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>

</body>

</html>
{% endblock %}